name: PD Test
on:
  push:
    branches:
      - master
      - release-4.0
      - release-5.*
      - release-6.*
      - release-7.*
      - release-8.*
  pull_request:
    branches:
      - master
      - release-4.0
      - release-5.*
      - release-6.*
      - release-7.*
      - release-8.*
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true
jobs:
  chunks:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        worker_id: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
    outputs:
      job-total: 13
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Make Test
        env:
          WORKER_ID: ${{ matrix.worker_id }}
          WORKER_COUNT: 13
          JOB_COUNT: 9 # 10 is tools test, 11, 12, 13 are for other integrations jobs
        run: |
          make ci-test-job JOB_COUNT=$(($JOB_COUNT)) JOB_INDEX=$WORKER_ID
          mv covprofile covprofile_$WORKER_ID
          sed -i "/failpoint_binding/d" covprofile_$WORKER_ID
      - name: Upload coverage result ${{ matrix.worker_id }}
        uses: actions/upload-artifact@v4
        with:
          name: cover-reports-${{ matrix.worker_id }}
          path: covprofile_${{ matrix.worker_id }}
  report-coverage:
    needs: chunks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download chunk report
        uses: actions/download-artifact@v4
        with:
          pattern: cover-reports-*
          merge-multiple: true
      - name: Merge
        env:
          TOTAL_JOBS: ${{needs.chunks.outputs.job-total}}
        run: for i in $(seq 1 $TOTAL_JOBS); do cat covprofile_$i >> covprofile; done
      - name: Send coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV }}
          file: ./covprofile
          flags: unittests
          name: codecov-umbrella
